# Generated by Django 5.0.3 on 2024-03-13 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode', models.CharField(max_length=50, verbose_name='Group Code')),
                ('comcode', models.CharField(max_length=50, verbose_name='Company Code')),
                ('brcode', models.CharField(max_length=50, verbose_name='Branch Code')),
                ('ucode', models.CharField(max_length=50, verbose_name='User Code')),
                ('trdate', models.DateTimeField(auto_now_add=True, verbose_name='Transation Date')),
                ('description', models.TextField(blank=True)),
                ('cusid', models.CharField(max_length=50, verbose_name='Customer Id')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('mname', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sal', models.CharField(max_length=20, verbose_name='Salutation')),
                ('aadhaar', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=20)),
                ('othidname', models.CharField(blank=True, max_length=50, verbose_name='Id Collected Name')),
                ('othid', models.CharField(blank=True, max_length=50, verbose_name='Id Collected Number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
