# Generated by Django 5.0.4 on 2024-04-15 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_brcode_alter_customer_comcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Invalid address format.', regex='[a-zA-Z0-9\\s.,#-]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Invalid address format.', regex='[a-zA-Z0-9\\s.,#-]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[a-zA-Z]+[a-zA-Z]$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[a-zA-Z]+[a-zA-Z]$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[a-zA-Z]+[a-zA-Z]$')], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[0-9]$')]),
        ),
    ]
