# Generated by Django 5.0.4 on 2024-04-16 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_address1_alter_customer_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='brcode',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comcode',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusid',
            field=models.CharField(max_length=50, unique=True, verbose_name='Customer Id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[a-zA-Z]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gcode',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Group Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[a-zA-Z]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters', regex='[a-zA-Z]+$')], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='This field must be 10 Numbers.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='This field must contain only Nuemeric characters', regex='[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ucode',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='User Code'),
        ),
    ]
