# Generated by Django 5.0.4 on 2024-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_brcode_alter_customer_comcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhaar',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
