# Generated by Django 5.0.4 on 2024-04-30 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_aadhaar_alter_customer_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='mob',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='This field must be 10 Numbers.', regex='^\\d{10}$')]),
        ),
    ]
