# Generated by Django 5.0.4 on 2024-05-10 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_imagemodel_alter_customer_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mob',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid p', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid p', regex='^\\d{10}$')]),
        ),
    ]
