# Generated by Django 5.0.4 on 2024-05-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_house_alter_customer_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='house',
            field=models.CharField(max_length=50),
        ),
    ]
