# Generated by Django 5.0.4 on 2024-04-13 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode', models.CharField(max_length=50, verbose_name='Group Code')),
                ('comcode', models.CharField(max_length=50, verbose_name='Company Code')),
                ('brcode', models.CharField(max_length=50, verbose_name='Branch Code')),
                ('ucode', models.CharField(max_length=50, verbose_name='User Code')),
                ('trdate', models.DateTimeField(auto_now_add=True, verbose_name='Transation Date')),
                ('description', models.TextField(blank=True)),
                ('rate', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
