# Generated by Django 5.0.4 on 2024-05-11 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldrate', '0004_alter_goldrate_brcode_alter_goldrate_comcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrate',
            name='brcode',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Branch Code'),
        ),
    ]
