# Generated by Django 5.0.4 on 2024-04-15 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='comcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Username only contain alphabets', regex='[a-zA-Z]$')]),
        ),
    ]
