# Generated by Django 5.0.4 on 2024-04-16 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_brcode_alter_user_comcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='comcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Username only contain alphabets', regex='[a-zA-Z]+$')]),
        ),
    ]
