# Generated by Django 5.0.4 on 2024-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_brcode_alter_user_comcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comcode',
            field=models.CharField(max_length=20),
        ),
    ]
