# Generated by Django 5.0.4 on 2024-05-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
