# Generated by Django 5.0.4 on 2024-05-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecode', '0003_city_country_code_city_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state_code',
        ),
    ]
