# Generated by Django 5.0.4 on 2024-05-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecode', '0004_remove_city_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_code',
        ),
    ]
