# Generated by Django 5.0.4 on 2024-04-16 07:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Group Code')),
                ('comcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Company Code')),
                ('brcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Branch Code')),
                ('ucode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='User Code')),
                ('trdate', models.DateTimeField(auto_now_add=True, verbose_name='Transation Date')),
                ('description', models.TextField(blank=True)),
                ('loanid', models.CharField(max_length=50, verbose_name='Loan Id')),
                ('fk_appid', models.CharField(max_length=50)),
                ('period', models.IntegerField()),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('duedate', models.DateTimeField()),
                ('Closed_date', models.DateField(default='1863-01-01')),
                ('closed_rate', models.FloatField()),
                ('status', models.CharField(default='N', max_length=10)),
                ('scheme', models.CharField(max_length=50)),
                ('gold_rate', models.FloatField()),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
