# Generated by Django 5.0.4 on 2024-04-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('comcode', models.CharField(max_length=20, unique=True, verbose_name='Company code')),
                ('comname', models.CharField(max_length=50, verbose_name='Company name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('brcode', models.CharField(max_length=20, verbose_name='Branch code')),
                ('brname', models.CharField(max_length=50, verbose_name='Branch name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companybranch.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
