# Generated by Django 5.0.4 on 2024-04-15 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companybranch', '0003_alter_branch_brname_alter_branch_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid address format.', regex='^[a-zA-Z0-9\\s.,#-]+$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='brcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]$')], verbose_name='Branch code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='brname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters and cannot start or end with spaces.', regex='[a-zA-Z]+[a-zA-Z]$')], verbose_name='Branch name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid address format.', regex='^[a-zA-Z0-9\\s.,#-]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='comcode',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]$')], verbose_name='Company code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only alphabetic characters and cannot start or end with spaces.', regex='[a-zA-Z]+[a-zA-Z]$')], verbose_name='Company name'),
        ),
    ]
