# Generated by Django 5.0.4 on 2024-04-16 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companybranch', '0004_alter_branch_address_alter_branch_brcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='brcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Branch code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comcode',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Company code cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Company code'),
        ),
    ]
