# Generated by Django 5.0.4 on 2024-04-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companybranch', '0008_alter_branch_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
    ]
