# Generated by Django 5.0.4 on 2024-04-11 05:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode', models.CharField(max_length=50, verbose_name='Group Code')),
                ('comcode', models.CharField(max_length=50, verbose_name='Company Code')),
                ('brcode', models.CharField(max_length=50, verbose_name='Branch Code')),
                ('ucode', models.CharField(max_length=50, verbose_name='User Code')),
                ('trdate', models.DateTimeField(auto_now_add=True, verbose_name='Transation Date')),
                ('description', models.TextField(blank=True)),
                ('hcode', models.CharField(max_length=80, verbose_name='Head code')),
                ('hcode1', models.CharField(max_length=80, verbose_name='Sub head')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('creadit', models.FloatField()),
                ('debit', models.FloatField()),
                ('vono', models.BigIntegerField(verbose_name='Voucher number')),
                ('type', models.CharField(max_length=80)),
                ('chkdate', models.DateTimeField(verbose_name='Check date')),
                ('chkno', models.CharField(max_length=80, verbose_name='Check number')),
                ('bank', models.CharField(max_length=80)),
                ('ifsc', models.CharField(max_length=80)),
                ('acno', models.CharField(max_length=20, verbose_name='Account number')),
                ('mode', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
