# Generated by Django 5.0.4 on 2024-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0003_alter_receiptpayment_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptpayment',
            name='type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt')], max_length=80),
        ),
    ]
