# Generated by Django 5.0.4 on 2024-04-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0005_alter_receiptpayment_acno_alter_receiptpayment_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptpayment',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receiptpayment',
            name='debit',
            field=models.FloatField(default=0),
        ),
    ]
