# Generated by Django 5.0.4 on 2024-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0006_alter_receiptpayment_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptpayment',
            name='type',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash')], max_length=100),
        ),
    ]
