# Generated by Django 5.0.4 on 2024-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0012_alter_bankentry_brcode_alter_bankentry_comcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='mode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
