# Generated by Django 5.0.4 on 2024-05-14 09:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0013_bankentry_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Group Code')),
                ('comcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Company Code')),
                ('brcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Branch Code')),
                ('ucode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='User Code')),
                ('trdate', models.DateTimeField(auto_now_add=True, verbose_name='Transation Date')),
                ('description', models.TextField(blank=True)),
                ('hcode', models.CharField(max_length=50)),
                ('tr_head', models.CharField(max_length=50, verbose_name='Account Head Code')),
                ('name', models.CharField(max_length=100, verbose_name='Party Name')),
                ('code', models.CharField(max_length=50)),
                ('code_from', models.CharField(max_length=50)),
                ('credit', models.FloatField()),
                ('debit', models.FloatField()),
                ('voucher_no', models.IntegerField()),
                ('cheque_no', models.CharField(max_length=50)),
                ('cheque_date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_acc_no', models.CharField(max_length=50)),
                ('ifse_code', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=50)),
                ('approved', models.BooleanField()),
                ('approvedby', models.CharField(max_length=50)),
                ('approvedtime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
