# Generated by Django 5.0.4 on 2024-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0014_daybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='approvedby',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='approvedtime',
            field=models.DateTimeField(blank=True),
        ),
    ]
