# Generated by Django 5.0.4 on 2024-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0015_alter_daybook_approvedby_alter_daybook_approvedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='approvedtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
