# Generated by Django 5.0.4 on 2024-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0016_alter_daybook_approvedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpimg', models.BinaryField()),
            ],
        ),
    ]
