# Generated by Django 5.0.4 on 2024-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0019_alter_receiptpayment_chkdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daybook',
            name='typ',
        ),
        migrations.AddField(
            model_name='daybook',
            name='type',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R')], default='', max_length=100),
        ),
    ]
