# Generated by Django 5.0.4 on 2024-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0020_remove_daybook_typ_daybook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='type',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R')], max_length=100),
        ),
    ]
