# Generated by Django 5.0.4 on 2024-05-16 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0023_rename_ifse_code_daybook_ifsc_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
