# Generated by Django 5.0.4 on 2024-05-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0024_typeoftransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeoftransaction',
            old_name='name',
            new_name='payment_name',
        ),
    ]
