# Generated by Django 5.0.4 on 2024-05-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0026_alter_daybook_bank_acc_no_alter_daybook_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt')], max_length=100),
        ),
    ]
