# Generated by Django 5.0.4 on 2024-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0028_alter_daybook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
