# Generated by Django 5.0.4 on 2024-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0029_alter_daybook_cheque_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
