# Generated by Django 5.0.4 on 2024-05-24 05:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0031_alter_daybook_voucher_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Group Code')),
                ('comcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Company Code')),
                ('brcode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='Branch Code')),
                ('ucode', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Field cannot contain special characters', regex='[a-zA-Z0-9]+$')], verbose_name='User Code')),
                ('trdate', models.DateTimeField(auto_now_add=True, verbose_name='Transation Date')),
                ('description', models.TextField(blank=True)),
                ('head_code', models.CharField(max_length=50, verbose_name='Account Head Code')),
                ('grouphead_id', models.CharField(max_length=100, verbose_name='head Name')),
                ('name', models.CharField(max_length=100, verbose_name='head Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
