# Generated by Django 5.0.4 on 2024-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0032_accountinghead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinghead',
            name='grouphead_id',
            field=models.CharField(max_length=100, verbose_name='Group head id'),
        ),
    ]
