# Generated by Django 5.0.4 on 2024-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0033_alter_accountinghead_grouphead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='code_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Party Name'),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='tr_head',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Head Code'),
        ),
    ]
