# Generated by Django 5.0.4 on 2024-05-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0037_alter_voucherhead_head_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinghead',
            name='head_code',
            field=models.CharField(max_length=50, verbose_name='Account Head Code'),
        ),
        migrations.AlterField(
            model_name='voucherhead',
            name='head_code',
            field=models.CharField(max_length=50),
        ),
    ]
