# Generated by Django 5.0.4 on 2024-05-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0040_voucherhead_head_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherhead',
            name='head_name',
            field=models.CharField(max_length=50),
        ),
    ]
