# Generated by Django 5.0.4 on 2024-05-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0041_alter_voucherhead_head_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherhead',
            name='head_name',
        ),
    ]
