# Generated by Django 5.0.4 on 2024-05-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0043_alter_daybook_cheque_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
