# Generated by Django 5.0.4 on 2024-05-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptpayment', '0044_alter_daybook_cheque_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='fk_AccountingHead',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='receiptpayment.accountinghead'),
        ),
    ]
